### ISSUE TITLE
191

### ISSUE THREAD

**Issue by DavEsp322** [JustDoom/MineCrash#4]
[crash-2022-09-08_17.50.38-server.txt](https://github.com/JustDoom/MineCrash/files/9529560/crash-2022-09-08_17.50.38-server.txt)

**Comment by JustDoom** [comment]
Did you have a solution to the error?

**Comment by DavEsp322** [comment]
GA, not really

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: jueves, 8 de septiembre de 2022 04:31 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [JustDoom/MineCrash] 191 (Issue #4)


Did you have a solution to the error?

**Comment by JustDoom** [comment]
Closed in favor of https://github.com/Eimer-Archive/MineCrashSolutions/issues (And not having a solution)
